import {Router} from 'express';
import EnderecoController from './app/controllers/EnderecoController';
import LocalController from './app/controllers/LocalController';

const router = Router();

//criando  rotas para /enderecos.
// http://localhost:3000/endereco/...
router.get('/endereco/list', EnderecoController.list);//define uma rota ... 
router.post('/endereco/store', EnderecoController.store);//define uma rota vai método post para chamar o método store da classe EnderecoController
router.get('/endereco/delete', EnderecoController.delete);//define uma rota ...
// http://localhost:3000/local/...
router.get('/local/list', LocalController.list);//define uma rota ... 
router.post('/local/store', LocalController.store);//define uma rota vai método post para chamar o método store da classe EnderecoController
router.get('/local/delete', LocalController.delete);//define uma rota ...

export default router;